"use client"

import { useRouter } from "next/navigation"
import { useState } from "react"
import { AlertCircle, Copy, Share } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { ProgressSteps } from "@/components/progress-steps"

interface ResponseItem {
  id: string
  modelName: string
  provider: string
  content: string
  responseTime: string
}

const prompt = "Summarize the key tradeoffs between building with a single LLM and an ensemble of LLMs."

const responses: ResponseItem[] = [
  {
    id: "gpt-4o",
    modelName: "GPT-4o",
    provider: "OpenAI",
    responseTime: "1242ms",
    content:
      "A single model is simpler and cheaper to orchestrate, but it concentrates failure modes. Ensembles improve robustness and perspective diversity at the cost of latency, complexity, and coordination overhead.",
  },
  {
    id: "gpt-4o-mini",
    modelName: "GPT-4o Mini",
    provider: "OpenAI",
    responseTime: "932ms",
    content:
      "Single-model systems are easier to debug and deploy. Ensembles can improve quality and reduce hallucination risk through disagreement analysis, but they require stronger observability and budget controls.",
  },
]

const consensusResponse =
  "Single-model setups optimize for speed and simplicity, while ensembles optimize for resilience and answer quality. The practical decision usually comes down to whether your product values deterministic throughput or decision confidence under uncertainty."

export default function ReviewPage() {
  const router = useRouter()
  const [ratings, setRatings] = useState<Record<string, number>>({})

  return (
    <div className="container mx-auto max-w-6xl px-4 py-8">
      <ProgressSteps currentStep="review" />

      <div className="text-center">
        <h2 className="text-3xl font-bold tracking-tight">Review Results</h2>
        <p className="mx-auto mt-3 max-w-3xl text-muted-foreground">Compare responses and analyze agreement.</p>
      </div>

      <div className="mt-8 space-y-8">
        <Card>
          <CardContent className="p-6">
            <h3 className="text-lg font-semibold">Your Prompt</h3>
            <div className="mt-4 rounded-lg bg-muted p-4">
              <p className="text-foreground">{prompt}</p>
            </div>
          </CardContent>
        </Card>

        <Card className="border-primary/20 bg-gradient-to-br from-primary/10 to-primary/5">
          <CardContent className="p-6">
            <div className="mb-4 flex items-center justify-between">
              <h3 className="text-lg font-semibold text-primary">Consensus</h3>
              <span className="rounded-full border border-primary/20 bg-background px-2 py-1 text-xs text-primary">
                Generated by GPT-4o
              </span>
            </div>

            <p className="rounded-lg bg-background p-4 leading-relaxed text-foreground">{consensusResponse}</p>

            <div className="mt-4 flex items-center justify-between border-t border-primary/20 pt-4">
              <button className="inline-flex items-center gap-1 text-sm text-primary hover:underline">
                <Copy className="h-4 w-4" />
                Copy
              </button>
              <div className="flex items-center gap-2">
                <Share className="h-4 w-4 text-primary" />
                <span className="text-sm text-primary">Share this consensus response</span>
                <Button variant="outline" size="sm">
                  Share
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-6">
            <div className="mb-6 flex items-center justify-between">
              <h3 className="text-lg font-semibold">Agreement analysis</h3>
              <div className="text-right">
                <p className="text-2xl font-bold text-amber-600">72%</p>
                <p className="text-sm text-muted-foreground">Overall Agreement</p>
                <p className="text-sm text-amber-600">Medium Agreement</p>
              </div>
            </div>

            <div className="mb-6 space-y-3">
              <p className="text-sm font-semibold">Pairwise Comparisons</p>
              <div className="flex items-center justify-between gap-4 text-sm">
                <div className="flex items-center gap-2">
                  <span>GPT-4o</span>
                  <span className="text-muted-foreground">vs</span>
                  <span>GPT-4o Mini</span>
                </div>
                <div className="flex items-center gap-3">
                  <div className="h-2 w-36 rounded-full bg-muted">
                    <div className="h-2 rounded-full bg-amber-500" style={{ width: "72%" }} />
                  </div>
                  <span className="font-medium">72%</span>
                  <span className="text-xs text-muted-foreground">Confidence: 91%</span>
                </div>
              </div>
            </div>

            <div className="grid grid-cols-3 gap-6 text-center">
              <div>
                <p className="text-2xl font-bold text-primary">2</p>
                <p className="text-xs text-muted-foreground">RESPONSES ANALYZED</p>
              </div>
              <div>
                <p className="text-2xl font-bold text-primary">1</p>
                <p className="text-xs text-muted-foreground">COMPARISONS</p>
              </div>
              <div>
                <p className="text-2xl font-bold text-primary">91%</p>
                <p className="text-xs text-muted-foreground">AVG CONFIDENCE</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <section className="space-y-4">
          <h3 className="text-xl font-semibold">AI Responses</h3>
          {responses.length === 0 ? (
            <div className="flex flex-col items-center rounded-lg border border-dashed bg-muted/30 p-12 text-center">
              <AlertCircle className="mb-4 h-12 w-12 text-muted-foreground" />
              <p className="text-lg font-semibold">No responses generated yet.</p>
              <p className="mt-2 max-w-md text-sm text-muted-foreground">
                Responses will appear here as models complete. Go back to submit a prompt.
              </p>
              <Button variant="outline" className="mt-6" onClick={() => router.push("/prompt")}>
                Back to Prompt
              </Button>
            </div>
          ) : (
            responses.map((response) => (
              <Card key={response.id}>
                <CardContent className="p-6">
                  <div className="mb-4 flex items-center justify-between">
                    <div>
                      <p className="font-semibold">{response.modelName}</p>
                      <p className="text-sm text-muted-foreground">{response.provider}</p>
                    </div>
                    <span className="text-sm text-muted-foreground">Response time: {response.responseTime}</span>
                  </div>

                  <p className="leading-relaxed text-foreground">{response.content}</p>

                  <div className="mt-4 flex items-center justify-between border-t pt-4">
                    <button className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground">
                      <Copy className="h-4 w-4" />
                      Copy
                    </button>
                    <div className="flex items-center gap-2 text-sm">
                      <span className="text-muted-foreground">Rate response:</span>
                      <div className="flex gap-1">
                        {[1, 2, 3, 4, 5].map((star) => (
                          <button
                            key={star}
                            type="button"
                            onClick={() => setRatings((prev) => ({ ...prev, [response.id]: star }))}
                            className={
                              star <= (ratings[response.id] ?? 0)
                                ? "text-yellow-500"
                                : "text-muted-foreground hover:text-yellow-500"
                            }
                          >
                            ★
                          </button>
                        ))}
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))
          )}
        </section>
      </div>

      <div className="mt-12 flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
        <div className="flex items-center gap-3">
          <Button variant="outline" onClick={() => router.push("/prompt")}>
            Back to Prompt
          </Button>
          <Button onClick={() => router.push("/config")}>Start Over</Button>
        </div>

        <Button variant="outline" onClick={() => router.push("/prompt")}>
          New Comparison
        </Button>
      </div>
    </div>
  )
}
