import { describe, it, expect, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { ConsensusCard } from './ConsensusCard';
import { renderWithI18n } from '../../../lib/test-utils/i18n-test-wrapper';

const mockConsensusText =
  'Your question has a clear focus that allows for a direct response. We can examine this through multiple lenses: theoretical foundations, real-world examples, and future considerations.';
const mockSummarizerModel = 'Claude 3 Opus';

describe('ConsensusCard', () => {
  describe('rendering', () => {
    it('renders the default heading', () => {
      render(
        <ConsensusCard consensusText={mockConsensusText} summarizerModel={mockSummarizerModel} />
      );

      expect(screen.getByText('Consensus')).toBeInTheDocument();
    });

    it('renders custom heading', () => {
      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          heading="Custom Consensus Heading"
        />
      );

      expect(screen.getByText('Custom Consensus Heading')).toBeInTheDocument();
    });

    it('renders the summarizer model in badge', () => {
      render(
        <ConsensusCard consensusText={mockConsensusText} summarizerModel={mockSummarizerModel} />
      );

      expect(screen.getByText(/Generated by Claude 3 Opus/)).toBeInTheDocument();
    });

    it('renders the consensus text', () => {
      render(
        <ConsensusCard consensusText={mockConsensusText} summarizerModel={mockSummarizerModel} />
      );

      expect(screen.getByText(mockConsensusText)).toBeInTheDocument();
    });

    it('renders copy button', () => {
      render(
        <ConsensusCard consensusText={mockConsensusText} summarizerModel={mockSummarizerModel} />
      );

      expect(screen.getByTestId('copy-button')).toBeInTheDocument();
      expect(screen.getByText('Copy')).toBeInTheDocument();
    });

    it('renders share button when onShare is provided', () => {
      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          onShare={() => { }}
        />
      );

      expect(screen.getByTestId('share-button')).toBeInTheDocument();
      expect(screen.getByText('Share')).toBeInTheDocument();
    });

    it('does not render share button when onShare is not provided', () => {
      render(
        <ConsensusCard consensusText={mockConsensusText} summarizerModel={mockSummarizerModel} />
      );

      expect(screen.queryByTestId('share-button')).not.toBeInTheDocument();
    });

    it('renders with testid', () => {
      render(
        <ConsensusCard consensusText={mockConsensusText} summarizerModel={mockSummarizerModel} />
      );

      expect(screen.getByTestId('consensus-card')).toBeInTheDocument();
    });
  });

  describe('styling', () => {
    it('applies gradient background to card', () => {
      render(
        <ConsensusCard consensusText={mockConsensusText} summarizerModel={mockSummarizerModel} />
      );

      const card = screen.getByTestId('consensus-card');
      expect(card).toHaveClass('bg-gradient-to-br');
    });

    it('applies primary text color to heading', () => {
      render(
        <ConsensusCard consensusText={mockConsensusText} summarizerModel={mockSummarizerModel} />
      );

      const heading = screen.getByText('Consensus');
      expect(heading).toHaveClass('text-primary');
    });

    it('applies correct heading styles', () => {
      render(
        <ConsensusCard consensusText={mockConsensusText} summarizerModel={mockSummarizerModel} />
      );

      const heading = screen.getByText('Consensus');
      expect(heading).toHaveClass('font-semibold');
    });

    it('applies card background to share button when provided', () => {
      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          onShare={() => { }}
        />
      );

      const shareButton = screen.getByTestId('share-button');
      expect(shareButton).toHaveClass('bg-card');
    });
  });

  describe('interactions', () => {
    it('calls onShare when share button is clicked', async () => {
      const onShare = vi.fn();
      const user = userEvent.setup();

      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          onShare={onShare}
        />
      );

      const shareButton = screen.getByTestId('share-button');
      await user.click(shareButton);

      expect(onShare).toHaveBeenCalledTimes(1);
    });

    it('handles multiple share button clicks', async () => {
      const onShare = vi.fn();
      const user = userEvent.setup();

      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          onShare={onShare}
        />
      );

      const shareButton = screen.getByTestId('share-button');
      await user.click(shareButton);
      await user.click(shareButton);
      await user.click(shareButton);

      expect(onShare).toHaveBeenCalledTimes(3);
    });

    it('copies text to clipboard when copy button is clicked', async () => {
      const user = userEvent.setup();
      const mockClipboard = { writeText: vi.fn().mockResolvedValue(undefined) };
      const originalClipboard = navigator.clipboard;
      Object.defineProperty(navigator, 'clipboard', { value: mockClipboard, writable: true });

      render(
        <ConsensusCard consensusText={mockConsensusText} summarizerModel={mockSummarizerModel} />
      );

      const copyButton = screen.getByTestId('copy-button');
      await user.click(copyButton);

      expect(mockClipboard.writeText).toHaveBeenCalledWith(mockConsensusText);
      Object.defineProperty(navigator, 'clipboard', { value: originalClipboard, writable: true });
    });

    it('shows Copied feedback after clicking copy', async () => {
      const user = userEvent.setup();
      const mockClipboard = { writeText: vi.fn().mockResolvedValue(undefined) };
      Object.defineProperty(navigator, 'clipboard', { value: mockClipboard, writable: true });

      render(
        <ConsensusCard consensusText={mockConsensusText} summarizerModel={mockSummarizerModel} />
      );

      const copyButton = screen.getByTestId('copy-button');
      await user.click(copyButton);

      expect(screen.getByText('Copied!')).toBeInTheDocument();
    });
  });

  describe('content variations', () => {
    it('handles long consensus text', () => {
      const longText = 'Lorem ipsum dolor sit amet.';

      render(<ConsensusCard consensusText={longText} summarizerModel={mockSummarizerModel} />);

      expect(screen.getByText(longText)).toBeInTheDocument();
    });

    it('handles short consensus text', () => {
      const shortText = 'Short summary.';

      render(<ConsensusCard consensusText={shortText} summarizerModel={mockSummarizerModel} />);

      expect(screen.getByText(shortText)).toBeInTheDocument();
    });

    it('handles different summarizer model names', () => {
      render(
        <ConsensusCard consensusText={mockConsensusText} summarizerModel="GPT-4 Turbo" />
      );

      expect(screen.getByText(/Generated by GPT-4 Turbo/)).toBeInTheDocument();
    });
  });

  describe('accessibility', () => {
    it('has semantic heading structure', () => {
      render(
        <ConsensusCard consensusText={mockConsensusText} summarizerModel={mockSummarizerModel} />
      );

      const heading = screen.getByRole('heading', { level: 3 });
      expect(heading).toHaveTextContent('Consensus');
    });

    it('has clickable copy button', () => {
      render(
        <ConsensusCard consensusText={mockConsensusText} summarizerModel={mockSummarizerModel} />
      );

      const button = screen.getByRole('button', { name: /Copy/i });
      expect(button).toBeInTheDocument();
    });

    it('has clickable share button when provided', () => {
      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          onShare={() => { }}
        />
      );

      const button = screen.getByRole('button', { name: /Share/i });
      expect(button).toBeInTheDocument();
    });
  });

  describe('layout', () => {
    it('renders in a card component', () => {
      const { container } = render(
        <ConsensusCard consensusText={mockConsensusText} summarizerModel={mockSummarizerModel} />
      );

      const card = container.querySelector('.rounded-xl');
      expect(card).toBeInTheDocument();
    });

    it('applies correct padding to card content', () => {
      const { container } = render(
        <ConsensusCard consensusText={mockConsensusText} summarizerModel={mockSummarizerModel} />
      );

      const cardContent = container.querySelector('.p-6');
      expect(cardContent).toBeInTheDocument();
    });

    it('renders footer section at bottom', () => {
      const { container } = render(
        <ConsensusCard consensusText={mockConsensusText} summarizerModel={mockSummarizerModel} />
      );

      const footerSection = container.querySelector('.flex.items-center.justify-between.mt-4');
      expect(footerSection).toBeInTheDocument();
    });
  });

  describe('edge cases', () => {
    it('returns null when no consensus text and not loading', () => {
      const { container } = render(<ConsensusCard consensusText="" summarizerModel={mockSummarizerModel} />);

      expect(container.firstChild).toBeNull();
    });

    it('renders when loading even without consensus text', () => {
      render(<ConsensusCard consensusText="" summarizerModel={mockSummarizerModel} isLoading={true} />);

      const card = screen.getByTestId('consensus-card');
      expect(card).toBeInTheDocument();
    });

    it('handles special characters in consensus text', () => {
      const specialText = 'Text with special chars: @#$%^&*()';

      render(<ConsensusCard consensusText={specialText} summarizerModel={mockSummarizerModel} />);

      expect(screen.getByText(specialText)).toBeInTheDocument();
    });

    it('handles special characters in summarizer model name', () => {
      const specialModel = 'Claude-3.5 (Opus)';

      render(<ConsensusCard consensusText={mockConsensusText} summarizerModel={specialModel} />);

      expect(screen.getByText(/Generated by Claude-3\.5 \(Opus\)/)).toBeInTheDocument();
    });
  });

  describe('internationalization', () => {
    it('renders English text', () => {
      renderWithI18n(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          onShare={() => { }}
        />,
        { language: 'en' }
      );
      expect(screen.getByText('Consensus')).toBeInTheDocument();
      expect(screen.getByText('Generated by Claude 3 Opus')).toBeInTheDocument();
      expect(screen.getByText('Share this consensus response')).toBeInTheDocument();
      expect(screen.getByText('Share')).toBeInTheDocument();
      expect(screen.getByText('Copy')).toBeInTheDocument();
    });

    it('renders French text', () => {
      renderWithI18n(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          onShare={() => { }}
        />,
        { language: 'fr' }
      );
      expect(screen.getByText('Consensus')).toBeInTheDocument();
      expect(screen.getByText(/Généré par Claude 3 Opus/)).toBeInTheDocument();
      expect(screen.getByText('Partager cette réponse consensuelle')).toBeInTheDocument();
      expect(screen.getByText('Partager')).toBeInTheDocument();
    });
  });
});
