import { describe, it, expect, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { ConsensusCard } from './ConsensusCard';
import { renderWithI18n } from '../../../lib/test-utils/i18n-test-wrapper';

const mockConsensusText =
  'Your question has a clear focus that allows for a direct response. We can examine this through multiple lenses: theoretical foundations, real-world examples, and future considerations.';
const mockSummarizerModel = 'Claude 3 Opus';

describe('ConsensusCard', () => {
  describe('rendering', () => {
    it('renders the default heading', () => {
      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          status="success"
        />
      );

      expect(screen.getByText('Consensus')).toBeInTheDocument();
    });

    it('renders custom heading', () => {
      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          status="success"
          heading="Custom Consensus Heading"
        />
      );

      expect(screen.getByText('Custom Consensus Heading')).toBeInTheDocument();
    });

    it('renders the summarizer model in badge', () => {
      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          status="success"
        />
      );

      expect(screen.getByText(/Generated by Claude 3 Opus/)).toBeInTheDocument();
    });

    it('renders the consensus text', () => {
      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          status="success"
        />
      );

      expect(screen.getByText(mockConsensusText)).toBeInTheDocument();
    });

    it('renders copy button in success state', () => {
      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          status="success"
        />
      );

      expect(screen.getByTestId('copy-button')).toBeInTheDocument();
      expect(screen.getByText('Copy')).toBeInTheDocument();
    });

    it('renders share button when onShare is provided', () => {
      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          status="success"
          onShare={() => {}}
        />
      );

      expect(screen.getByTestId('share-button')).toBeInTheDocument();
      expect(screen.getByText('Share')).toBeInTheDocument();
    });

    it('does not render share button when onShare is not provided', () => {
      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          status="success"
        />
      );

      expect(screen.queryByTestId('share-button')).not.toBeInTheDocument();
    });

    it('renders with testid', () => {
      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          status="success"
        />
      );

      expect(screen.getByTestId('consensus-card')).toBeInTheDocument();
    });
  });

  describe('styling', () => {
    it('applies gradient background to card', () => {
      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          status="success"
        />
      );

      const card = screen.getByTestId('consensus-card');
      expect(card).toBeInTheDocument();
    });

    it('renders heading', () => {
      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          status="success"
        />
      );

      const heading = screen.getByText('Consensus');
      expect(heading).toBeInTheDocument();
    });

    it('applies card background to share button when provided', () => {
      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          status="success"
          onShare={() => {}}
        />
      );

      const shareButton = screen.getByTestId('share-button');
      expect(shareButton).toBeInTheDocument();
    });
  });

  describe('interactions', () => {
    it('calls onShare when share button is clicked', async () => {
      const onShare = vi.fn();
      const user = userEvent.setup();

      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          status="success"
          onShare={onShare}
        />
      );

      const shareButton = screen.getByTestId('share-button');
      await user.click(shareButton);

      expect(onShare).toHaveBeenCalledTimes(1);
    });

    it('handles multiple share button clicks', async () => {
      const onShare = vi.fn();
      const user = userEvent.setup();

      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          status="success"
          onShare={onShare}
        />
      );

      const shareButton = screen.getByTestId('share-button');
      await user.click(shareButton);
      await user.click(shareButton);
      await user.click(shareButton);

      expect(onShare).toHaveBeenCalledTimes(3);
    });

    it('copies text to clipboard when copy button is clicked', async () => {
      const user = userEvent.setup();
      const mockClipboard = { writeText: vi.fn().mockResolvedValue(undefined) };
      const originalClipboard = navigator.clipboard;
      Object.defineProperty(navigator, 'clipboard', { value: mockClipboard, writable: true });

      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          status="success"
        />
      );

      const copyButton = screen.getByTestId('copy-button');
      await user.click(copyButton);

      expect(mockClipboard.writeText).toHaveBeenCalledWith(mockConsensusText);
      Object.defineProperty(navigator, 'clipboard', { value: originalClipboard, writable: true });
    });

    it('shows Copied feedback after clicking copy', async () => {
      const user = userEvent.setup();
      const mockClipboard = { writeText: vi.fn().mockResolvedValue(undefined) };
      Object.defineProperty(navigator, 'clipboard', { value: mockClipboard, writable: true });

      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          status="success"
        />
      );

      const copyButton = screen.getByTestId('copy-button');
      await user.click(copyButton);

      expect(screen.getByText('Copied!')).toBeInTheDocument();
    });
  });

  describe('content variations', () => {
    it('handles long consensus text', () => {
      const longText = 'Lorem ipsum dolor sit amet.';

      render(
        <ConsensusCard consensusText={longText} summarizerModel={mockSummarizerModel} status="success" />
      );

      expect(screen.getByText(longText)).toBeInTheDocument();
    });

    it('handles short consensus text', () => {
      const shortText = 'Short summary.';

      render(
        <ConsensusCard consensusText={shortText} summarizerModel={mockSummarizerModel} status="success" />
      );

      expect(screen.getByText(shortText)).toBeInTheDocument();
    });

    it('handles different summarizer model names', () => {
      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel="GPT-4 Turbo"
          status="success"
        />
      );

      expect(screen.getByText(/Generated by GPT-4 Turbo/)).toBeInTheDocument();
    });
  });

  describe('accessibility', () => {
    it('has semantic heading structure', () => {
      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          status="success"
        />
      );

      const heading = screen.getByRole('heading', { level: 3 });
      expect(heading).toHaveTextContent('Consensus');
    });

    it('has clickable copy button', () => {
      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          status="success"
        />
      );

      const button = screen.getByRole('button', { name: /Copy/i });
      expect(button).toBeInTheDocument();
    });

    it('has clickable share button when provided', () => {
      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          status="success"
          onShare={() => {}}
        />
      );

      const button = screen.getByRole('button', { name: /Share/i });
      expect(button).toBeInTheDocument();
    });
  });

  describe('layout', () => {
    it('renders in a card component', () => {
      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          status="success"
        />
      );

      expect(screen.getByTestId('consensus-card')).toBeInTheDocument();
    });

    it('renders card content', () => {
      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          status="success"
        />
      );

      expect(screen.getByTestId('consensus-card')).toBeInTheDocument();
    });

    it('renders footer section in success state', () => {
      const { container } = render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          status="success"
        />
      );

      const footer = container.querySelector('[data-testid="consensus-footer"]');
      expect(footer).toBeInTheDocument();
    });
  });

  describe('edge cases', () => {
    it('handles special characters in consensus text', () => {
      const specialText = 'Text with special chars: @#$%^&*()';

      render(
        <ConsensusCard
          consensusText={specialText}
          summarizerModel={mockSummarizerModel}
          status="success"
        />
      );

      expect(screen.getByText(specialText)).toBeInTheDocument();
    });

    it('handles special characters in summarizer model name', () => {
      const specialModel = 'Claude-3.5 (Opus)';

      render(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={specialModel}
          status="success"
        />
      );

      expect(screen.getByText(/Generated by Claude-3\.5 \(Opus\)/)).toBeInTheDocument();
    });
  });

  describe('internationalization', () => {
    it('renders English text', () => {
      renderWithI18n(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          status="success"
          onShare={() => {}}
        />,
        { language: 'en' }
      );
      expect(screen.getByText('Consensus')).toBeInTheDocument();
      expect(screen.getByText('Generated by Claude 3 Opus')).toBeInTheDocument();
      expect(screen.getByText('Share this consensus response')).toBeInTheDocument();
      expect(screen.getByText('Share')).toBeInTheDocument();
      expect(screen.getByText('Copy')).toBeInTheDocument();
    });

    it('renders French text', () => {
      renderWithI18n(
        <ConsensusCard
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
          status="success"
          onShare={() => {}}
        />,
        { language: 'fr' }
      );
      expect(screen.getByText('Consensus')).toBeInTheDocument();
      expect(screen.getByText(/Généré par Claude 3 Opus/)).toBeInTheDocument();
      expect(screen.getByText('Partager cette réponse consensuelle')).toBeInTheDocument();
      expect(screen.getByText('Partager')).toBeInTheDocument();
    });
  });

  describe('status states', () => {
    it('renders awaiting state with message', () => {
      renderWithI18n(
        <ConsensusCard status="awaiting" summarizerModel={mockSummarizerModel} />,
        { language: 'en' }
      );

      expect(screen.getByTestId('consensus-card')).toBeInTheDocument();
      expect(screen.getByText(/awaiting model responses/i)).toBeInTheDocument();
    });

    it('renders awaiting state description', () => {
      renderWithI18n(
        <ConsensusCard status="awaiting" summarizerModel={mockSummarizerModel} />,
        { language: 'en' }
      );

      expect(screen.getByText(/consensus summary will be generated/i)).toBeInTheDocument();
    });

    it('renders generating state with skeleton', () => {
      renderWithI18n(
        <ConsensusCard status="generating" summarizerModel={mockSummarizerModel} />,
        { language: 'en' }
      );

      expect(screen.getByTestId('consensus-card')).toBeInTheDocument();
      expect(screen.getByText(/generating consensus/i)).toBeInTheDocument();
      expect(screen.getByTestId('consensus-skeleton')).toBeInTheDocument();
    });

    it('renders success state with consensus text', () => {
      renderWithI18n(
        <ConsensusCard
          status="success"
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
        />,
        { language: 'en' }
      );

      expect(screen.getByText(mockConsensusText)).toBeInTheDocument();
      expect(screen.getByTestId('copy-button')).toBeInTheDocument();
    });

    it('renders failed state with error message', () => {
      const errorMessage = 'API rate limit exceeded';
      renderWithI18n(
        <ConsensusCard
          status="failed"
          error={errorMessage}
          summarizerModel={mockSummarizerModel}
        />,
        { language: 'en' }
      );

      expect(screen.getByTestId('consensus-card')).toBeInTheDocument();
      expect(screen.getByText(/failed to generate consensus/i)).toBeInTheDocument();
      expect(screen.getByText(errorMessage)).toBeInTheDocument();
    });

    it('renders failed state without error details', () => {
      renderWithI18n(
        <ConsensusCard status="failed" summarizerModel={mockSummarizerModel} />,
        { language: 'en' }
      );

      expect(screen.getByText(/failed to generate consensus/i)).toBeInTheDocument();
    });

    it('hides copy/share buttons in non-success states', () => {
      const { rerender } = renderWithI18n(
        <ConsensusCard status="awaiting" summarizerModel={mockSummarizerModel} />,
        { language: 'en' }
      );
      expect(screen.queryByTestId('copy-button')).not.toBeInTheDocument();

      rerender(
        <ConsensusCard status="generating" summarizerModel={mockSummarizerModel} />
      );
      expect(screen.queryByTestId('copy-button')).not.toBeInTheDocument();

      rerender(
        <ConsensusCard status="failed" summarizerModel={mockSummarizerModel} />
      );
      expect(screen.queryByTestId('copy-button')).not.toBeInTheDocument();
    });
  });

  describe('status transitions', () => {
    it('transitions from awaiting to generating', () => {
      const { rerender } = renderWithI18n(
        <ConsensusCard status="awaiting" summarizerModel={mockSummarizerModel} />,
        { language: 'en' }
      );
      expect(screen.getByText(/awaiting/i)).toBeInTheDocument();

      rerender(
        <ConsensusCard status="generating" summarizerModel={mockSummarizerModel} />
      );
      expect(screen.getByText(/generating/i)).toBeInTheDocument();
    });

    it('transitions from generating to success', () => {
      const { rerender } = renderWithI18n(
        <ConsensusCard status="generating" summarizerModel={mockSummarizerModel} />,
        { language: 'en' }
      );

      rerender(
        <ConsensusCard
          status="success"
          consensusText={mockConsensusText}
          summarizerModel={mockSummarizerModel}
        />
      );
      expect(screen.getByText(mockConsensusText)).toBeInTheDocument();
    });

    it('can transition to failed from any state', () => {
      const { rerender } = renderWithI18n(
        <ConsensusCard status="awaiting" summarizerModel={mockSummarizerModel} />,
        { language: 'en' }
      );

      rerender(
        <ConsensusCard
          status="failed"
          error="Something went wrong"
          summarizerModel={mockSummarizerModel}
        />
      );
      expect(screen.getByText(/failed/i)).toBeInTheDocument();
    });
  });
});
